package reports

import (
	"context"
	"fmt"
	"fortistack/internal/alerts"
	"fortistack/internal/risk"
	"fortistack/internal/tenants"
	"time"
)

type Service struct {
	Repo         *Repository
	TenantRepo   *tenants.Repository
	PDFGenerator *PDFGenerator
	RiskEngine   func(risk.Input) risk.Report
	AlertService *alerts.Service
}

func NewService(repo *Repository, tenantRepo *tenants.Repository, alerts *alerts.Service) *Service {
	return &Service{
		Repo:         repo,
		TenantRepo:   tenantRepo,
		PDFGenerator: NewPDFGenerator(),
		RiskEngine:   risk.CalculateRisk,
		AlertService: alerts,
	}
}

func (s *Service) GenerateSnapshot(ctx context.Context, tenantID string, input risk.Input) (*Report, error) {
	// 1. Get Tenant for name
	t, err := s.TenantRepo.Get(ctx, tenantID)
	if err != nil {
		return nil, fmt.Errorf("failed to get tenant: %w", err)
	}
	if t == nil {
		return nil, fmt.Errorf("tenant not found: %s", tenantID)
	}

	// 2. Calculate Risk
	riskReport := s.RiskEngine(input)

	// 3. Create Report Structure
	report := &Report{
		TenantID:    tenantID,
		TenantName:  t.Name,
		ReportType:  TypeSnapshot,
		GlobalScore: riskReport.Score.Global,
		CreatedAt:   time.Now(),
		Details:     &riskReport,
	}

	// 4. Render HTML
	htmlContent, err := Render(report)
	if err != nil {
		return nil, fmt.Errorf("render failed: %w", err)
	}

	// 5. Generate PDF
	// Use timestamp component for file name
	reportID := fmt.Sprintf("snap-%s-%d", tenantID, time.Now().Unix())
	pdfPath, err := s.PDFGenerator.Generate(ctx, htmlContent, reportID)
	if err != nil {
		return nil, fmt.Errorf("pdf generation failed: %w", err)
	}

	report.ID = reportID // Not DB ID yet, but useful for filename?
	// Wait, DB ID is UUID generated by DB in `Repo.Save`.
	// So `reportID` used for filename is distinct or derived.
	// `PDFGenerator` returns the path.
	report.StoragePath = pdfPath

	// 6. Save to DB (this sets report.ID to UUID)
	if err := s.Repo.Save(ctx, report); err != nil {
		return nil, fmt.Errorf("db save failed: %w", err)
	}

	// 7. Send Alert
	go func() {
		alertCtx, cancel := context.WithTimeout(context.Background(), 1*time.Minute)
		defer cancel()
		// Passing generated PDF storage path as "download URL" or "report ID" depending on implementation.
		// alerts.Service expects something to turn into URL.
		// If we pass report.ID (UUID), alerts.Service can build /reports/{uuid}/download.
		if err := s.AlertService.SendAlerts(alertCtx, report.TenantID, string(report.ReportType), report.GlobalScore, report.ID, riskReport.Findings); err != nil {
			fmt.Printf("failed to send alerts for tenant %s: %v\n", tenantID, err)
		}
	}()

	return report, nil
}

func (s *Service) GenerateMonthly(ctx context.Context, tenantID string, start, end time.Time, input risk.Input) (*Report, error) {
	t, err := s.TenantRepo.Get(ctx, tenantID)
	if err != nil {
		return nil, fmt.Errorf("failed to get tenant: %w", err)
	}
	if t == nil {
		return nil, fmt.Errorf("tenant not found: %s", tenantID)
	}

	riskReport := s.RiskEngine(input)

	report := &Report{
		TenantID:          tenantID,
		TenantName:        t.Name,
		ReportType:        TypeMonthly,
		ReportPeriodStart: &start,
		ReportPeriodEnd:   &end,
		GlobalScore:       riskReport.Score.Global,
		CreatedAt:         time.Now(),
		Details:           &riskReport,
	}

	htmlContent, err := Render(report)
	if err != nil {
		return nil, fmt.Errorf("render failed: %w", err)
	}

	reportFileID := fmt.Sprintf("monthly-%s-%d", tenantID, time.Now().Unix())
	pdfPath, err := s.PDFGenerator.Generate(ctx, htmlContent, reportFileID)
	if err != nil {
		return nil, fmt.Errorf("pdf generation failed: %w", err)
	}
	report.StoragePath = pdfPath

	if err := s.Repo.Save(ctx, report); err != nil {
		return nil, fmt.Errorf("db save failed: %w", err)
	}

	go func() {
		alertCtx, cancel := context.WithTimeout(context.Background(), 1*time.Minute)
		defer cancel()
		if err := s.AlertService.SendAlerts(alertCtx, report.TenantID, string(report.ReportType), report.GlobalScore, report.ID, riskReport.Findings); err != nil {
			fmt.Printf("failed to send alerts for tenant %s: %v\n", tenantID, err)
		}
	}()

	return report, nil
}

func (s *Service) GetReports(ctx context.Context, tenantID string) ([]Report, error) {
	return s.Repo.GetByTenantID(ctx, tenantID, 50)
}

func (s *Service) GetReport(ctx context.Context, reportID string) (*Report, error) {
	return s.Repo.GetOne(ctx, reportID)
}

func (s *Service) GetReportDownload(ctx context.Context, reportID string) (string, error) {
	report, err := s.Repo.GetOne(ctx, reportID)
	if err != nil {
		return "", err
	}
	if report == nil {
		return "", fmt.Errorf("report not found")
	}
	// Return local file path
	return report.StoragePath, nil
}
